spring:
  application:
    name: estonian-crossword-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/crossword_db
    username: crossword_user
    password: strong_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080